name: runtime
description: Runtime server for function execution
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  function_types:
    git: https://github.com/lohanidamodar/function_types
  shelf: ^1.2.0
